services:
  web:
    image: "${GA_IMAGE:-ghcr.io/aymankastali/go_auth:latest}"
    restart: always
    ports:
      - "${GA_HTTP_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy