# =========================
# Stage 1 — Lint
# =========================
FROM golangci/golangci-lint:v2.8.0 AS linter
WORKDIR /workspace
COPY go.mod go.sum ./
COPY ./cmd ./cmd
COPY ./internal ./internal
RUN golangci-lint run ./...

# =========================
# Stage 2 — Build
# =========================
FROM golang:1.25 AS builder
RUN apt-get update && apt-get install -y git ca-certificates build-essential
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY ./cmd ./cmd
COPY ./internal ./internal
RUN go build -o /main ./cmd/server/main.go

# =========================
# Stage 3 — Final runtime image
# =========================
FROM golang:1.25 AS runtime
RUN apt-get update && apt-get install -y git bash
WORKDIR /workspace
COPY --from=builder /main /main
EXPOSE 8080
USER root
ENTRYPOINT ["/main"]