services:
  web:
    image: "${GA_APP_NAME}:latest"
    build:
      context: .
      dockerfile: build/Dockerfile.prod
    restart: always
    ports:
      - "${GA_HTTP_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy