package fiberapp

import (
	"context"
	"go_auth/internal/application"
	"log/slog"

	"github.com/gofiber/fiber/v3"
	"github.com/gofiber/fiber/v3/middleware/requestid"
)

func ContextMiddleware(baseLogger *slog.Logger) fiber.Handler {
	return func(c fiber.Ctx) error {
		// 1. Pull the ID generated by the Fiber requestid middleware
		reqID := requestid.FromContext(c)

		// 2. Create a logger SCOPED to this request ID
		// Every log inside a Use Case will now use this exact req_id
		scopedLogger := baseLogger.With(slog.String("req_id", reqID))

		// 3. Re-inject the scoped logger into our domain context
		rc, err := NewRequestContext(
			reqID,
			c.IP(),
			c.Get("Accept-Language"),
			c.Get("User-Agent"),
			scopedLogger,
		)
		if err != nil {
			return err
		}

		ctx := context.WithValue(c.Context(), requestCtxKey, rc)
		ctx = application.WithAppContext(ctx, rc.AppContext())
		c.SetContext(ctx)

		return c.Next()
	}
}
