FROM golang:1.25

RUN go install github.com/go-delve/delve/cmd/dlv@latest \
    && go install github.com/swaggo/swag/cmd/swag@latest \
    && go install github.com/air-verse/air@latest \
    && curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.8.0

WORKDIR /app
