package fiberapp

import (
	"context"
	"errors"
	"go_auth/internal/core/application"
	"go_auth/internal/core/pkg/err"
	"log/slog"

	"github.com/gofiber/fiber/v3"
	"github.com/gofiber/fiber/v3/middleware/logger"
	"github.com/gofiber/fiber/v3/middleware/requestid"
)

func ContextMiddleware(baseLogger *slog.Logger) fiber.Handler {
	return func(c fiber.Ctx) error {
		// 1. Pull the ID generated by the Fiber requestid middleware
		reqID := requestid.FromContext(c)

		// 2. Create a logger SCOPED to this request ID
		// Every log inside a Use Case will now use this exact req_id
		scopedLogger := baseLogger.With(slog.String("req_id", reqID))

		// 3. Re-inject the scoped logger into our domain context
		rc, err := NewRequestContext(
			reqID,
			c.IP(),
			c.Get("Accept-Language"),
			c.Get("User-Agent"),
			scopedLogger,
		)
		if err != nil {
			return err
		}

		ctx := context.WithValue(c.Context(), requestCtxKey, rc)
		ctx = application.WithAppContext(ctx, rc.AppContext())
		c.SetContext(ctx)

		return c.Next()
	}
}

func Protected(validateUC application.IValidateAccessUseCase) fiber.Handler {
	return func(c fiber.Ctx) error {
		logger := application.GetLogger(c.Context())

		token := extractToken(c.Get("Authorization"))
		if token == "" {
			logger.Warn("authorization_attempt_missing_token")
			return fiber.NewError(fiber.StatusUnauthorized, "missing authorization header")
		}

		access, err := validateUC.Execute(c.Context(), application.ValidateAccessQuery{
			AccessToken: token,
			Fingerprint: c.Get("X-Fingerprint"),
		})
		if err != nil {
			// UseCase already logs internal details, so we just return
			return err
		}

		rc, err := FromContext(c.Context())
		if err != nil {
			logger.Error("context_lost_during_protection_middleware")
			return err
		}

		if err := rc.AttachUser(access.UserID, access.SessionID); err != nil {
			logger.Error("failed_to_attach_user_to_context", slog.Any("error", err))
			return err
		}

		c.SetContext(application.WithAppContext(c.Context(), rc.AppContext()))

		logger.Debug("request_authenticated", slog.String("user_id", access.UserID))
		return c.Next()
	}
}

func ConfigureMiddlewares(app *fiber.App, baseLogger *slog.Logger, idGen application.IIDGenerator) {
	// 1. Trace ID / Request ID
	app.Use(requestid.New(requestid.Config{
		Generator: func() string {
			id, _ := idGen.Generate()
			return id
		},
	}))

	// 2. Access Logging
	app.Use(logger.New(logger.Config{
		Format:     `{"time":"${time}", "ip":"${ip}", "req_id":"${respHeader:X-Request-ID}", "method":"${method}", "url":"${url}", "status":${status}}` + "\n",
		TimeFormat: "2006-01-02T15:04:05.000Z",
		TimeZone:   "UTC",
	}))

	// 3. Domain Context & Error Handling
	app.Use(ContextMiddleware(baseLogger))
}

// Error Handler
func NewErrorHandler() fiber.ErrorHandler {
	return func(c fiber.Ctx, e error) error {
		// Use the helper here as the primary source of truth
		traceID := requestid.FromContext(c)
		if traceID == "" {
			traceID = "unknown"
		}

		resp := ErrorResponse{
			TraceID: traceID,
			Code:    string(err.CodeInternal),
			Message: "Internal server error",
		}
		statusCode := fiber.StatusInternalServerError

		var appErr *err.Error
		if errors.As(e, &appErr) {
			resp.Code = string(appErr.Code())
			resp.Message = appErr.Message()
			statusCode = mapCodeToHTTPStatus(appErr.Code())

			logRequestError(c, statusCode, e)
			return c.Status(statusCode).JSON(resp)
		}

		var fErr *fiber.Error
		if errors.As(e, &fErr) {
			statusCode = fErr.Code
			resp.Code = "TRANSPORT_ERROR"
			resp.Message = fErr.Message
			logRequestError(c, statusCode, e)
			return c.Status(statusCode).JSON(resp)
		}

		logRequestError(c, statusCode, e)
		return c.Status(statusCode).JSON(resp)
	}
}
