package fiberapp

import (
	"context"
	"errors"
	"go_auth/internal/core/application"
	"log/slog"

	"github.com/gofiber/fiber/v3"
	"github.com/gofiber/fiber/v3/middleware/requestid"
)

func AppErrorMiddleware() fiber.Handler {
	return func(c fiber.Ctx) error {
		err := c.Next()
		if err == nil {
			return nil
		}

		var fErr *fiber.Error
		if errors.As(err, &fErr) {
			return fErr
		}

		// Logging is handled in the global ErrorHandler,
		// so we just transform the error here.
		return application.MapToAppError(err)
	}
}

func ContextMiddleware(baseLogger *slog.Logger) fiber.Handler {
	return func(c fiber.Ctx) error {
		// 1. Pull the ID generated by the Fiber requestid middleware
		reqID := requestid.FromContext(c)

		// 2. Create a logger SCOPED to this request ID
		// Every log inside a Use Case will now use this exact req_id
		scopedLogger := baseLogger.With(slog.String("req_id", reqID))

		// 3. Re-inject the scoped logger into our domain context
		rc, err := NewRequestContext(
			reqID,
			c.IP(),
			c.Get("Accept-Language"),
			c.Get("User-Agent"),
			scopedLogger,
		)
		if err != nil {
			return err
		}

		ctx := context.WithValue(c.Context(), requestCtxKey, rc)
		ctx = application.WithAppContext(ctx, rc.AppContext())
		c.SetContext(ctx)

		return c.Next()
	}
}

func Protected(validateUC application.IValidateAccessUseCase) fiber.Handler {
	return func(c fiber.Ctx) error {
		logger := application.GetLogger(c.Context())

		token := extractToken(c.Get("Authorization"))
		if token == "" {
			logger.Warn("authorization_attempt_missing_token")
			return fiber.NewError(fiber.StatusUnauthorized, "missing authorization header")
		}

		access, err := validateUC.Execute(c.Context(), application.ValidateAccessQuery{
			AccessToken: token,
			Fingerprint: c.Get("X-Fingerprint"),
		})
		if err != nil {
			// UseCase already logs internal details, so we just return
			return err
		}

		rc, err := FromContext(c.Context())
		if err != nil {
			logger.Error("context_lost_during_protection_middleware")
			return err
		}

		if err := rc.AttachUser(access.UserID, access.SessionID); err != nil {
			logger.Error("failed_to_attach_user_to_context", slog.Any("error", err))
			return err
		}

		c.SetContext(application.WithAppContext(c.Context(), rc.AppContext()))

		logger.Debug("request_authenticated", slog.String("user_id", access.UserID))
		return c.Next()
	}
}

func NewErrorHandler() fiber.ErrorHandler {
	return func(c fiber.Ctx, err error) error {
		ctx := c.Context()
		logger := application.GetLogger(ctx)

		var traceID = "unknown"

		if rc, err := FromContext(ctx); err == nil {
			traceID = rc.requestID
		}

		var (
			statusCode = fiber.StatusInternalServerError
			resp       = ErrorResponse{TraceID: traceID}
			appErr     *application.AppError
		)

		if errors.As(err, &appErr) {
			resp.Code = string(appErr.Code)
			resp.Message = appErr.Message
			statusCode = mapAppErrorToStatus(appErr.Code)

			// Log Domain/Logic errors as Warnings (expected failures)
			logger.Warn("http_request_handled_with_error",
				slog.Int("status", statusCode),
				slog.String("app_code", resp.Code),
				slog.String("method", c.Method()),
				slog.String("path", c.Path()),
				slog.Any("err_internal", appErr.Err),
			)
		} else {
			// Log Unexpected/System errors as Errors
			logger.Error("http_request_system_failure",
				slog.Int("status", statusCode),
				slog.String("method", c.Method()),
				slog.String("path", c.Path()),
				slog.Any("error", err),
			)
			resp.Message = "Internal server error"
		}

		return c.Status(statusCode).JSON(resp)
	}
}
