package fiberapp

import (
	"context"
	"errors"
	"go_auth/internal/core/application"
	"go_auth/internal/core/domain"
	"log/slog"

	"github.com/gofiber/fiber/v3"
	"github.com/gofiber/fiber/v3/middleware/logger"
	"github.com/gofiber/fiber/v3/middleware/requestid"
)

func AppErrorMiddleware() fiber.Handler {
	return func(c fiber.Ctx) error {
		err := c.Next()
		if err == nil {
			return nil
		}

		var fErr *fiber.Error
		if errors.As(err, &fErr) {
			return fErr
		}

		// Logging is handled in the global ErrorHandler,
		// so we just transform the error here.
		return application.MapToAppError(err)
	}
}

func ContextMiddleware(baseLogger *slog.Logger) fiber.Handler {
	return func(c fiber.Ctx) error {
		// 1. Pull the ID generated by the Fiber requestid middleware
		reqID := requestid.FromContext(c)

		// 2. Create a logger SCOPED to this request ID
		// Every log inside a Use Case will now use this exact req_id
		scopedLogger := baseLogger.With(slog.String("req_id", reqID))

		// 3. Re-inject the scoped logger into our domain context
		rc, err := NewRequestContext(
			reqID,
			c.IP(),
			c.Get("Accept-Language"),
			c.Get("User-Agent"),
			scopedLogger,
		)
		if err != nil {
			return err
		}

		ctx := context.WithValue(c.Context(), requestCtxKey, rc)
		ctx = application.WithAppContext(ctx, rc.AppContext())
		c.SetContext(ctx)

		return c.Next()
	}
}

func Protected(validateUC application.IValidateAccessUseCase) fiber.Handler {
	return func(c fiber.Ctx) error {
		logger := application.GetLogger(c.Context())

		token := extractToken(c.Get("Authorization"))
		if token == "" {
			logger.Warn("authorization_attempt_missing_token")
			return fiber.NewError(fiber.StatusUnauthorized, "missing authorization header")
		}

		access, err := validateUC.Execute(c.Context(), application.ValidateAccessQuery{
			AccessToken: token,
			Fingerprint: c.Get("X-Fingerprint"),
		})
		if err != nil {
			// UseCase already logs internal details, so we just return
			return err
		}

		rc, err := FromContext(c.Context())
		if err != nil {
			logger.Error("context_lost_during_protection_middleware")
			return err
		}

		if err := rc.AttachUser(access.UserID, access.SessionID); err != nil {
			logger.Error("failed_to_attach_user_to_context", slog.Any("error", err))
			return err
		}

		c.SetContext(application.WithAppContext(c.Context(), rc.AppContext()))

		logger.Debug("request_authenticated", slog.String("user_id", access.UserID))
		return c.Next()
	}
}

func NewErrorHandler() fiber.ErrorHandler {
	return func(c fiber.Ctx, err error) error {
		ctx := c.Context()
		logger := application.GetLogger(ctx)

		var traceID = "unknown"
		if rc, rcErr := FromContext(ctx); rcErr == nil {
			traceID = rc.requestID
		}

		var (
			statusCode = fiber.StatusInternalServerError
			resp       = ErrorResponse{TraceID: traceID}
		)

		// Handle AppError
		var appErr *application.AppError
		if errors.As(err, &appErr) {
			if appErr.Code == "" {
				appErr.Code = application.AppErrInternal
			}
			resp.Code = string(appErr.Code)
			resp.Message = appErr.Message
			statusCode = mapAppErrorToStatus(appErr.Code)

			logger.Warn("http_request_handled_with_error",
				slog.Int("status", statusCode),
				slog.String("app_code", resp.Code),
				slog.String("method", c.Method()),
				slog.String("path", c.Path()),
				slog.Any("err_internal", appErr.Err),
			)
			return c.Status(statusCode).JSON(resp)
		}

		// Handle Fiber errors (like 404 for unknown route)
		var fErr *fiber.Error
		if errors.As(err, &fErr) {
			resp.Code = mapFiberStatusToAppCode(fErr.Code)
			resp.Message = fErr.Message
			statusCode = fErr.Code

			logger.Warn("http_request_fiber_error",
				slog.Int("status", statusCode),
				slog.String("app_code", resp.Code),
				slog.String("method", c.Method()),
				slog.String("path", c.Path()),
				slog.Any("err_internal", fErr),
			)
			return c.Status(statusCode).JSON(resp)
		}

		// Fallback for unknown/system errors
		resp.Code = string(application.AppErrInternal)
		resp.Message = "Internal server error"
		logger.Error("http_request_system_failure",
			slog.Int("status", statusCode),
			slog.String("method", c.Method()),
			slog.String("path", c.Path()),
			slog.Any("error", err),
		)
		return c.Status(statusCode).JSON(resp)
	}
}
func ConfigureMiddlewares(app *fiber.App, baseLogger *slog.Logger, idGen domain.IIDGenerator) {
	// 1. Trace ID / Request ID
	app.Use(requestid.New(requestid.Config{
		Generator: func() string {
			id, _ := idGen.Generate()
			return id
		},
	}))

	// 2. Access Logging
	app.Use(logger.New(logger.Config{
		Format:     `{"time":"${time}", "ip":"${ip}", "req_id":"${respHeader:X-Request-ID}", "method":"${method}", "url":"${url}", "status":${status}}` + "\n",
		TimeFormat: "2006-01-02T15:04:05.000Z",
		TimeZone:   "UTC",
	}))

	// 3. Domain Context & Error Handling
	app.Use(ContextMiddleware(baseLogger))
	app.Use(AppErrorMiddleware())
}

func mapFiberStatusToAppCode(status int) string {
	switch status {
	case fiber.StatusBadRequest:
		return string(application.AppErrUnprocessable)
	case fiber.StatusUnauthorized:
		return string(application.AppErrUnauthorized)
	case fiber.StatusForbidden:
		return string(application.AppErrForbidden)
	case fiber.StatusNotFound:
		return string(application.AppErrNotFound)
	case fiber.StatusConflict:
		return string(application.AppErrConflict)
	default:
		return string(application.AppErrInternal)
	}
}
